<% if ENV['DB_HOST'] %>
default_settings: &default_settings
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 32
  timeout: 5000

development:
  <<: *default_settings

production:
  <<: *default_settings
<% else %>
development:
  adapter: postgresql
  database: appa_dev
  pool: 32
  timeout: 5000

test:
  adapter: postgresql
  database: appa_test
  pool: 32
  timeout: 5000

production:
  adapter: postgresql
  database: appa_prod
  pool: 32
  timeout: 5000
<% end %>