<% if ENV['DB_HOST'] %>
default_settings: &default_settings
  adapter: postgresql
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= (ENV['JOB_CONCURRENCY'] || 4).to_i + 16 %>
  timeout: 5000

development:
  <<: *default_settings

production:
  <<: *default_settings
<% else %>
default_settings: &default_settings
  adapter: postgresql
  pool: <%= (ENV['JOB_CONCURRENCY'] || 4).to_i + 16 %>
  timeout: 5000

development:
  <<: *default_settings
  database: appa_dev

test:
  <<: *default_settings
  database: appa_test

production:
  <<: *default_settings
  database: appa_prod
<% end %>